secrets: /config/secrets.yaml
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  disable_apps: 1
  plugins:
    HASS:
      type: hass
      ha_url: http://66c4055fd9fb.sn.mynetname.net:48123
      ha_key: !secret http_password
hadashboard:
  dash_url: http://127.0.0.1:5050
  dash_dir: /config/appdaemon/dashboards
