- action:
  - delay: 00:02:00
  - data:
      entity_id: media_player.tts_kodi
      message: I have detected a disturbance in the force, oh welcome home Lord Tina.
    service: tts.google_say
  alias: Welcome Home Tina
  condition: []
  id: '1518583395434'
  trigger:
  - entity_id: device_tracker.admin_iphone
    event: enter
    platform: zone
    zone: zone.home
- action:
  - service: script.refresh_devices
  alias: Owntracks Refresh
  condition: []
  id: '1518583750645'
  trigger:
    minutes: /5
    seconds: 0
    platform: time
- action:
  - delay: 00:02:00
  - data:
      entity_id: media_player.tts_kodi
      message: Welcome home James your arrival has caused a disturbance in the force.
    service: tts.google_say
  alias: Welcome Home James
  condition: []
  id: '1518584011710'
  trigger:
  - entity_id: device_tracker.admin_samsung
    event: enter
    platform: zone
    zone: zone.home
- action:
  - service: frontend.set_theme
    data:
      name: midnight
  alias: Set Theme to Midnight
  condition: []
  id: '1518991140056'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      entity_id: media_player.tts_kodi
      message: Daddy has arrived safely at work.
    service: tts.google_say
  alias: Dad at Work
  condition: []
  id: '1520218344569'
  trigger:
  - entity_id: device_tracker.admin_samsung
    event: enter
    platform: zone
    zone: zone.powertec
- action:
  - data:
      entity_id: media_player.tts_kodi
      message: Daddy is 25 minutes from home.
    service: tts.google_say
  alias: Work to Home 25min Notify
  condition:
  - after: '13:00'
    condition: time
  id: '1520227116276'
  trigger:
  - entity_id: device_tracker.admin_samsung
    event: enter
    platform: zone
    zone: zone.work_home_beacon_25mins
- action:
  - data:
      entity_id: media_player.tts_kodi
      message: Daddy has left work and is on his way home, with normal traffic he
        should be 40 minutes.
    service: tts.google_say
  alias: Daddy Leaving Work Notify
  condition:
  - after: '14:00'
    condition: time
  id: '1520227297161'
  trigger:
  - entity_id: device_tracker.admin_samsung
    event: leave
    platform: zone
    zone: zone.powertec
- action:
  - data:
      entity_id: media_player.tts_kodi
      message: Daddy will be home in 15 minutes.
    service: tts.google_say
  alias: Work to Home 15mins Notify
  condition:
  - after: '13:00'
    condition: time
  id: '1520227376239'
  trigger:
  - entity_id: device_tracker.admin_samsung
    event: enter
    platform: zone
    zone: zone.work_home_beacon_15mins
- action:
  - data:
      entity_id: media_player.tts_kodi
      message: Warning Warning Warning, Daddy will be home in 5 minutes.
    service: tts.google_say
  alias: Work to Home 5min Notify
  condition: []
  id: '1520227515826'
  trigger:
  - entity_id: device_tracker.admin_samsung
    event: enter
    platform: zone
    zone: zone.work_home_beacon_5mins
- action:
  - service: script.1521695181969
  - data:
      entity_id: media_player.tts_kodi
      message: Lounge Fan Off
    service: tts.google_say
  alias: Lounge Fan Off
  condition: []
  id: '1520362782660'
  trigger:
  - entity_id: input_select.lounge_fan
    platform: state
    to: Fan Off
- action:
  - service: script.1521695117457
  - data:
      entity_id: media_player.tts_kodi
      message: Fan Speed Low
    service: tts.google_say
  alias: Lounge Fan Low
  condition: []
  id: '1520363110688'
  trigger:
  - entity_id: input_select.lounge_fan
    platform: state
    to: Low
- action:
  - service: script.1521695035815
  - data:
      entity_id: media_player.tts_kodi
      message: Fan Speed Medium
    service: tts.google_say
  alias: Lounge Fan Medium
  condition: []
  id: '1520363174895'
  trigger:
  - entity_id: input_select.lounge_fan
    platform: state
    to: Medium
- action:
  - service: script.1521694972303
  - data:
      entity_id: media_player.tts_kodi
      message: Fan Speed High
    service: tts.google_say
  alias: Lounge Fan High
  condition: []
  id: '1520363214499'
  trigger:
  - entity_id: input_select.lounge_fan
    platform: state
    to: High
- action:
  - data:
      entity_id: scene.climate_off
    service: scene.turn_on
  - data:
      entity_id: media_player.tts_kodi
      message: Downstairs Climate Off.
    service: tts.google_say
  alias: Lounge Climate Off
  condition: []
  id: '1520374946876'
  trigger:
  - entity_id: input_select.lounge_aircon
    platform: state
    to: Climate Off
- action:
  - data:
      entity_id: scene.climate_cool
    service: scene.turn_on
  - data:
      entity_id: media_player.tts_kodi
      message: Climate Control On lets cool this place down.
    service: tts.google_say
  alias: Lounge Climate Cool
  condition: []
  id: '1520375237905'
  trigger:
  - entity_id: input_select.lounge_aircon
    platform: state
    to: Cool
- action:
  - data:
      entity_id: scene.climate_heat
    service: scene.turn_on
  - data:
      entity_id: media_player.tts_kodi
      message: Climate Control On lets warm this place up.
    service: tts.google_say
  alias: Lounge Climate Heat
  condition: []
  id: '1520375408449'
  trigger:
  - entity_id: input_select.lounge_aircon
    platform: state
    to: Heat
- action:
  - service: script.1521695238080
  alias: Bedroom Fan High
  condition: []
  id: '1521312736298'
  trigger:
  - entity_id: input_select.bedroom_fan
    platform: state
    to: High
- action:
  - service: script.1521695283264
  alias: Bedroom Fan Medium
  condition: []
  id: '1521312809495'
  trigger:
  - entity_id: input_select.bedroom_fan
    platform: state
    to: Medium
- action:
  - service: script.1521695486416
  alias: Bedroom Fan Low
  condition: []
  id: '1521312849850'
  trigger:
  - entity_id: input_select.bedroom_fan
    platform: state
    to: Low
- action:
  - data:
      entity_id: input_select.bedroom_fan
    service: input_select.select_next
  alias: Bedside Fan Switch
  condition: []
  id: '1521929634797'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000233a19d
    event_type: click
    platform: event
- action:
  - service: script.1521695537041
  alias: Bedroom Fan Off
  condition: []
  id: '1521953991104'
  trigger:
  - entity_id: input_select.bedroom_fan
    platform: state
    to: Fan Off
- action:
  - data:
      entity_id: input_select.bedroom_fan
    service: input_select.select_next
  alias: Bedroom Fan Wall Switch
  condition: []
  id: '1521955249707'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000215aa27
    event_type: click
    platform: event
- action:
  - data:
      entity_id: light.gateway_light_7811dcfd812f
    service: light.turn_on
  alias: TV Back Light On
  condition: []
  id: '1521955477992'
  trigger:
  - entity_id: sun.sun
    platform: state
    to: below_horizon
- action:
  - data:
      entity_id: light.gateway_light_7811dcfd812f
    service: light.turn_off
  alias: TV Back Light Off
  condition: []
  id: '1521955525110'
  trigger:
  - at: '22:00'
    platform: time
- action:
  - data:
      entity_id: switch.patio_light_switch
    service: switch.turn_on
  - delay: 00:02:00
  - data:
      entity_id: switch.patio_light_switch
    service: switch.turn_off
  alias: Patio Motion Light
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1522176123532'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000200ea5b
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: input_select.lounge_fan
    service: input_select.select_next
  alias: Lounge Wall Fan Switch
  condition: []
  id: '1522176462153'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000201ce4e
    event_type: click
    platform: event
- action:
  - data:
      entity_id: media_player.media_4k_kodi
    service: media_player.media_pause
  - data:
      entity_id: switch.media_tv_pause
    service: switch.turn_on
  alias: Door Bell Pressed
  condition: []
  id: '1522178372086'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000213108e
    event_type: click
    platform: event
- action:
  - data:
      entity_id: light.entrance_bulb
    service: light.turn_on
  - delay: 00:02:00
  - data:
      entity_id: light.entrance_bulb
    service: light.turn_off
  alias: Entry Motion Light
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1522739411963'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e5d147
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: scene.livingroom_dim
    service: scene.turn_on
  alias: Dim Lights for Lounge Media
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - after: '19:00'
    before: 04:00
    condition: time
  id: '1522871099565'
  trigger:
  - entity_id: media_player.media_4k_kodi
    from: idle
    platform: state
    to: playing
- action:
  - data:
      entity_id: scene.livingroom_normal
    service: scene.turn_on
  alias: Light Normal After Media
  condition:
  - condition: state
    entity_id: light.lounge_bulb
    state: 'on'
  id: '1522871608621'
  trigger:
  - entity_id: media_player.media_4k_kodi
    from: playing
    platform: state
    to: idle
- action:
  - data:
      entity_id: scene.livingroom_dim
    service: scene.turn_on
  - data:
      entity_id: scene.livingroom_normal
    service: scene.turn_on
  alias: Door Bell Pressed - Night
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1522873158041'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000213108e
    event_type: click
    platform: event
- action:
  - data:
      entity_id: scene.livingroom_dim
    service: scene.turn_on
  alias: Dim Lights for Lounge Media - Paused
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - after: '19:00'
    before: 04:00
    condition: time
  id: '1522873431655'
  trigger:
  - entity_id: media_player.media_4k_kodi
    from: paused
    platform: state
    to: playing
- action:
  - data:
      entity_id: scene.livingroom_normal
    service: scene.turn_on
  alias: Light Normal Media Paused
  condition:
  - condition: state
    entity_id: light.lounge_bulb
    state: 'on'
  id: '1522873533154'
  trigger:
  - entity_id: media_player.media_4k_kodi
    from: playing
    platform: state
    to: paused
- action:
  - data:
      entity_id: scene.hall_dusk
    service: scene.turn_on
  alias: Hall Light On
  condition: []
  id: '1523387114452'
  trigger:
  - entity_id: sun.sun
    platform: state
    to: below_horizon
- action:
  - data:
      entity_id: scene.hall_normal
    service: scene.turn_on
  alias: Hall Light Normal
  condition: []
  id: '1523387234695'
  trigger:
  - event: sunset
    offset: '30:00'
    platform: sun
- action:
  - data:
      entity_id: scene.hall_dim
    service: scene.turn_on
  alias: Hall Light Dim
  condition: []
  id: '1523387361492'
  trigger:
  - at: '18:30'
    platform: time
- action:
  - data:
      entity_id: light.hall_bulb
    service: light.turn_off
  alias: Hall Light Off
  condition: []
  id: '1523387457800'
  trigger:
  - event: sunrise
    offset: '60:00'
    platform: sun
- action:
  - service: script.1523505263098
  alias: Playroom Fan Level 1
  condition: []
  id: '1523506259174'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 1
- action:
  - service: script.1523505294052
  alias: Playroom Fan Level 2
  condition: []
  id: '1523506309171'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 2
- action:
  - service: script.1523505324933
  alias: Playroom Fan Level 3
  condition: []
  id: '1523506362068'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 3
- action:
  - service: script.1523505358220
  alias: Playroom Fan Level 4
  condition: []
  id: '1523506407302'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 4
- action:
  - data:
      entity_id: switch.plug_158d0001f24e2b
    service: switch.turn_off
  alias: Entertainment Lighting
  condition: []
  id: '1523592899521'
  trigger:
  - event: sunset
    offset: '1:00:00'
    platform: sun
- action:
  - data:
      entity_id: switch.plug_158d0001f24e2b
    service: switch.turn_off
  alias: Entertainment Lighting Off
  condition: []
  id: '1523593293453'
  trigger:
  - at: '18:45'
    platform: time
- action:
  - service: script.1523649643350
  alias: Fairy Lights On
  condition: []
  id: '1523650164600'
  trigger:
  - event: sunset
    offset: 00:30
    platform: sun
- action:
  - data:
      entity_id: switch.fairy_light_power
    service: switch.turn_off
  alias: Fairy Lights Off
  condition: []
  id: '1523650257993'
  trigger:
  - at: '22:00'
    platform: time
- action:
  - data:
      entity_id: switch.plug_158d00022ae22d
    service: switch.turn_on
  - delay: 04:00
  - data:
      entity_id: switch.plug_158d00022ae22d
    service: switch.turn_off
  alias: Appliance Charging Overnight
  condition: []
  id: '1524319348801'
  trigger:
  - at: 01:00
    platform: time
- action:
  - service: script.1524684263950
  alias: Playroom Fan Oscillation On
  condition: []
  id: '1524684408949'
  trigger:
  - entity_id: input_select.playroom_fan_oscillate
    platform: state
    to: 'On'
- action:
  - service: script.1524684295834
  alias: Playroom Fan Oscillation Off
  condition: []
  id: '1524684465276'
  trigger:
  - entity_id: input_select.playroom_fan_oscillate
    platform: state
    to: 'Off'
- action:
  - service: script.1524684610404
  alias: Playroom Fan Left
  condition: []
  id: '1524684755156'
  trigger:
  - entity_id: input_select.playroom_fan_direction
    platform: state
    to: Left
- action:
  - service: script.1524684637559
  alias: Playroom Fan Right
  condition: []
  id: '1524684794880'
  trigger:
  - entity_id: input_select.playroom_fan_direction
    platform: state
    to: Right
- action:
  - service: script.1524685492627
  alias: Playroom Fan Angle 30°
  condition: []
  id: '1524685692186'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 30°
- action:
  - service: script.1524685531855
  alias: Playroom Fan Angle 60°
  condition: []
  id: '1524685738008'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 60°
- action:
  - service: script.1524685564893
  alias: Playroom Fan Angle 90°
  condition: []
  id: '1524685781740'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 90°
- action:
  - service: script.1524685607962
  alias: Playroom Fan Angle 120°
  condition: []
  id: '1524685824683'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 120°
- action:
  - service: script.1524685935022
  alias: Playroom Fan Natural Mode On
  condition: []
  id: '1524686015510'
  trigger:
  - entity_id: input_select.playroom_fan_natural_mode
    platform: state
    to: 'On'
- action:
  - service: script.1524685962145
  alias: Playroom Fan Natural Mode Off
  condition: []
  id: '1524686061379'
  trigger:
  - entity_id: input_select.playroom_fan_natural_mode
    platform: state
    to: 'Off'
- action:
  - service: script.1524686151270
  alias: Playroom Fan LED 0
  condition: []
  id: '1524686270827'
  trigger:
  - entity_id: input_select.playroom_fan_led_brightness
    platform: state
    to: '0'
- action:
  - service: script.1524686188825
  alias: Playroom Fan LED 1
  condition: []
  id: '1524686315547'
  trigger:
  - entity_id: input_select.playroom_fan_led_brightness
    platform: state
    to: '1'
- action:
  - service: script.1524686216404
  alias: Playroom Fan LED 2
  condition: []
  id: '1524686360333'
  trigger:
  - entity_id: input_select.playroom_fan_led_brightness
    platform: state
    to: '2'
