####################################################
#                                                  #
#                TP-Link Cameras                   #
#                                                  #
####################################################

- platform: generic
  still_image_url: http://10.0.10.1:8080/stream/snapshot.jpg
  name: Baby Monitor
  username: admin
  password: !secret camera_password
  authentication: digest