
core_router:
  hide_if_away: false
  icon:
  mac:
  name: core router
  picture:
  track: true
  vendor:

nas_movies:
  hide_if_away: false
  icon:
  mac:
  name: nas movies
  picture:
  track: true
  vendor:

nas_tv:
  hide_if_away: false
  icon:
  mac:
  name: nas tv
  picture:
  track: true
  vendor:

core_switch:
  hide_if_away: false
  icon:
  mac:
  name: core switch
  picture:
  track: true
  vendor:

upstairs_switch:
  hide_if_away: false
  icon:
  mac:
  name: upstairs switch
  picture:
  track: true
  vendor:

wifi_bridge:
  hide_if_away: false
  icon:
  mac:
  name: wifi bridge
  picture:
  track: true
  vendor:

cambium_ap:
  hide_if_away: false
  icon:
  mac:
  name: cambium ap
  picture:
  track: true
  vendor:

5g_ac_main:
  hide_if_away: false
  icon:
  mac:
  name: 5g ac main
  picture:
  track: true
  vendor:

5g_ac_media_tv:
  hide_if_away: false
  icon:
  mac:
  name: 5g ac media tv
  picture:
  track: true
  vendor:

5g_ac_upstairs:
  hide_if_away: false
  icon:
  mac:
  name: 5g ac upstairs
  picture:
  track: true
  vendor:

printer:
  hide_if_away: false
  icon:
  mac:
  name: printer
  picture:
  track: true
  vendor:

media_kodi_4k:
  hide_if_away: false
  icon:
  mac:
  name: media kodi 4k
  picture:
  track: true
  vendor:

hdhomerun:
  hide_if_away: false
  icon:
  mac:
  name: hdhomerun
  picture:
  track: true
  vendor:

appletv:
  hide_if_away: false
  icon:
  mac:
  name: appletv
  picture:
  track: true
  vendor:

admin_samsung:
  hide_if_away: false
  icon:
  mac:
  name: James
  picture: /local/james.jpg
  track: true
  vendor:

admin_iphone:
  hide_if_away: false
  icon:
  mac:
  name: Tina
  picture: /local/tina.jpg
  track: true
  vendor:

baby_monitor_camera:
  hide_if_away: false
  icon:
  mac:
  name: baby monitor camera
  picture:
  track: true
  vendor:

smart_things_hub:
  hide_if_away: false
  icon:
  mac:
  name: smart things hub
  picture:
  track: true
  vendor:

rpi:
  hide_if_away: false
  icon:
  mac:
  name: rpi
  picture:
  track: true
  vendor:

xiaomi_gateway:
  hide_if_away: false
  icon:
  mac:
  name: xiaomi gateway
  picture:
  track: true
  vendor:

ir_blaster_downstairs:
  hide_if_away: false
  icon:
  mac:
  name: ir blaster downstairs
  picture:
  track: true
  vendor:

ir_blaster_upstairs:
  hide_if_away: false
  icon:
  mac:
  name: ir blaster upstairs
  picture:
  track: true
  vendor:

temp_sensor_downstairs:
  hide_if_away: false
  icon:
  mac:
  name: temp sensor downstairs
  picture:
  track: true
  vendor:

8c89a5ef4d19:
  hide_if_away: false
  icon:
  mac: Main PC
  name: 8c89a5ef4d19
  picture:
  track: true
  vendor: Micro-Star INT'L CO., LTD

f081735c7ffc:
  hide_if_away: false
  icon:
  mac: F0:81:73:5C:7F:FC
  name: Amazon Dot Bedroom
  picture:
  track: true
  vendor: unknown

temp_sensor_playroom:
  hide_if_away: false
  icon:
  mac:
  name: temp sensor playroom
  picture:
  track: true
  vendor:

44650df543ec:
  hide_if_away: false
  icon:
  mac: 44:65:0D:F5:43:EC
  name: Amazon Echo
  picture:
  track: true
  vendor: Amazon Technologies Inc.

lounge_light_bulb:
  hide_if_away: false
  icon:
  mac:
  name: lounge light bulb
  picture:
  track: true
  vendor:

lounge_fan_switch:
  hide_if_away: false
  icon:
  mac:
  name: lounge fan switch
  picture:
  track: true
  vendor:

kitchen_dining_light_switch:
  hide_if_away: false
  icon:
  mac:
  name: kitchen dining light switch
  picture:
  track: true
  vendor:

patio_light_switch:
  hide_if_away: false
  icon:
  mac:
  name: patio light switch
  picture:
  track: true
  vendor:

lounge_light_switch:
  hide_if_away: false
  icon:
  mac:
  name: lounge light switch
  picture:
  track: true
  vendor:

temp_sensor_master_bedroom:
  hide_if_away: false
  icon:
  mac:
  name: temp sensor master bedroom
  picture:
  track: true
  vendor:

media_tv:
  hide_if_away: false
  icon:
  mac:
  name: media tv
  picture:
  track: true
  vendor:

hall_light_bulb:
  hide_if_away: false
  icon:
  mac:
  name: hall light bulb
  picture:
  track: true
  vendor:

garden_pi:
  hide_if_away: false
  icon:
  mac:
  name: garden pi
  picture:
  track: true
  vendor:

master_bedroom_fan_switch:
  hide_if_away: false
  icon:
  mac:
  name: master bedroom fan switch
  picture:
  track: true
  vendor:

kitchen_dashboard:
  hide_if_away: false
  icon:
  mac:
  name: kitchen dashboard
  picture:
  track: true
  vendor:

8c89a5ef4d19_2:
  hide_if_away: false
  icon:
  mac: 8C:89:A5:EF:4D:19
  name: 8c89a5ef4d19 2
  picture:
  track: true
  vendor: Micro-Star INT'L CO., LTD

entry_light_bulb:
  hide_if_away: false
  icon:
  mac:
  name: entry light bulb
  picture:
  track: true
  vendor:

dining_light_bulb:
  hide_if_away: false
  icon:
  mac:
  name: dining light bulb
  picture:
  track: true
  vendor:

patio_led_switch:
  hide_if_away: false
  icon:
  mac:
  name: patio led switch
  picture:
  track: true
  vendor:

playroom_fan:
  hide_if_away: false
  icon:
  mac:
  name: playroom fan
  picture:
  track: true
  vendor:

bedroom_kodi:
  hide_if_away: false
  icon:
  mac:
  name: bedroom kodi
  picture:
  track: true
  vendor:

downstairs_camera:
  hide_if_away: false
  icon:
  mac:
  name: downstairs camera
  picture:
  track: true
  vendor:

robovac:
  hide_if_away: false
  icon:
  mac:
  name: robovac
  picture:
  track: true
  vendor:

patio_kodi:
  hide_if_away: false
  icon:
  mac:
  name: patio kodi
  picture:
  track: true
  vendor:

bedroom_tv:
  hide_if_away: false
  icon:
  mac:
  name: bedroom tv
  picture:
  track: true
  vendor:

alarm_panel:
  hide_if_away: false
  icon:
  mac:
  name: alarm panel
  picture:
  track: true
  vendor:
