####################################################
#                                                  #
#                     Sonoff                       #
#                                                  #
####################################################

- alias: Living Room
  platform: mqtt
  name: "Living Room Lamp"
  state_topic: "stat/sonoff-light-lounge/POWER"
  command_topic: "cmnd/sonoff-light-lounge/power"
  payload_on: "ON"
  payload_off: "OFF"
  
####################################################
#                                                  #
#                    Phillips                      #
#                                                  #
####################################################

- platform: xiaomi_miio
  name: Entrance Bulb
  host: !secret ent_bulb_ip
  token: !secret ent_bulb_token
  model: philips.light.bulb
  
- platform: xiaomi_miio
  name: Lounge Bulb
  host: !secret lounge_bulb_ip
  token: !secret lounge_bulb_token
  model: philips.light.bulb
  
- platform: xiaomi_miio
  name: Dining Bulb
  host: !secret dining_bulb_ip
  token: !secret dining_bulb_token
  model: philips.light.bulb
  
- platform: xiaomi_miio
  name: Hall Bulb
  host: !secret hall_bulb_ip
  token: !secret hall_bulb_token
  model: philips.light.bulb
  
