####################################################
#                                                  #
#                      Kodi                        #
#                                                  #
####################################################

- platform: kodi
  host: !secret media_kodi_ip
  name: Media 4K Kodi
  
- platform: kodi
  host: !secret bedroom_kodi_ip
  name: Bedroom Kodi
  
- platform: kodi
  host: !secret patio_kodi_ip
  name: Patio Kodi
  
- platform: kodi
  host: !secret tts_kodi_ip
  name: TTS Kodi
  username: kodi
  password: kodi
  
####################################################
#                                                  #
#                    Samsung TV                    #
#                                                  #
####################################################

- platform: samsungtv
  host: !secret media_tv_ip
  port: 8001
  name: Media 4K TV
  mac: !secret media_tv_mac
  
- platform: samsungtv
  host: !secret bed_tv_ip
  name: Bedroom TV
