####################################################
#                                                  #
#                     Android                      #
#                                                  #
####################################################

  - name: Galaxy_Tab_A_(2016)
    platform: lannouncer
    host: 10.0.6.3
    
####################################################
#                                                  #
#                      Kodi                        #
#                                                  #
####################################################
   
  - platform: kodi
    host: 10.0.3.1   
    port: 8080                   
    name: TTS_Kodi                    
    username: kodi            
    password: kodi