# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
http_password: Aut0MAT3!
name: Kingia Castle
latitude: -28.1081439
longitude: 153.4402859
elevation: 6
timezone: Australia/Brisbane
mikrotik_user: admin
mikrotik_pass: bheads2014
wunderground_api: 3eabb4512af567b3
wunderground_pws_id: IGOLDCOA25
james_work_latitude: -27.9752276
james_work_longitude: 153.3800853
kindy_latitude: -28.0998194
kindy_longitude: 153.44331
wb_latitude: -28.143161
wb_longitude: 153.4943654
stocklands_latitude: -28.0974658
stocklands_longitude: 153.4405604
parlour_latitude: -28.1127969
parlour_longitude: 153.4415485 
workhome25mins_latitude: -28.0106551
workhome25mins_longitude: 153.3697837
workhome15mins_latitude: -28.0355653
workhome15mins_longitude: 153.4087944
workhome5mins_latitude: -28.1001210
workhome5mins_longitude: 153.4259605
camera_password: Bheads4220
google_maps: AIzaSyAwT2S3aEz0vHuAOcfV6-d8ILTjhZEfPeo
cloudmqttuser: ha
cloudmqttpass: ha
mozzieuser: admin
mozziepass: Aut0MAT3!