- name: Powertec
  latitude: !secret james_work_latitude
  longitude: !secret james_work_longitude
  radius: 250
  icon: mdi:briefcase
  
- name: Kindy
  latitude: !secret kindy_latitude
  longitude: !secret kindy_longitude
  radius: 50
  icon: mdi:school
  
- name: Whole Beings
  latitude: !secret wb_latitude
  longitude: !secret wb_longitude
  radius: 250
  icon: mdi:school
  
- name: Stocklands
  latitude: !secret stocklands_latitude
  longitude: !secret stocklands_longitude
  radius: 200
  icon: mdi:cart
  
- name: Parlour
  latitude: !secret parlour_latitude
  longitude: !secret parlour_longitude
  radius: 50
  icon: mdi:coffee
  
- name: Work Home Beacon 25mins
  latitude: !secret workhome25mins_latitude
  longitude: !secret workhome25mins_longitude
  radius: 50
  icon: mdi:car
  
- name: Work Home Beacon 15mins
  latitude: !secret workhome15mins_latitude
  longitude: !secret workhome15mins_longitude
  radius: 50
  icon: mdi:car
  
- name: Work Home Beacon 5mins
  latitude: !secret workhome5mins_latitude
  longitude: !secret workhome5mins_longitude
  radius: 50
  icon: mdi:car